export const HOME = "/";
export const PRODUCTS_LIST = "/productsList/:productCategory";
export const PRODUCT_DETAIL = "/product/";
export const MENS_CLOTHING = "men clothing";
export const JEWELLERY = "jewelery";
export const ELECTRONICS = "electronics";
export const WOMENS_CLOTHING = "women clothing";
export const KIDS_CLOTHING = "women clothing";
export const CARTDEMO = "/cartdemo";
